name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Run format check
        run: uv run ruff format --check

      - name: Run lint
        run: uv run ruff check

      - name: Run type check
        run: uv run mypy src/

      - name: Run test
        run: uv run python -m tests.main -v
